version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: cicdproject_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: moviesdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  app:
    image: cicdproject
    container_name: cicdproject
    build: .
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
        - ./config/application.properties:/app/src/main/resources/application-prod.properties

volumes:
  postgres_data:


