apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: cicdproject-namespace
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM= # base64 encoded 'postgres'
  POSTGRES_PASSWORD: cG9zdGdyZXM= # base64 encoded 'postgres'
  POSTGRES_DB: bW92aWVzZGI= # base64 encoded 'moviesdb'