name: CI/CD pipeline

on:
  push:
    branches:
      - master  # Run on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      # Build the application using Maven
      - name: Build with Maven
        run: mvn clean package

      # Log in to DockerHub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker image using docker-compose
      - name: Build Docker image
        run: docker-compose -f docker-compose.yml build

      # Push Docker image to DockerHub using docker-compose
      - name: Push Docker image to DockerHub
        run: docker-compose -f docker-compose.yml push

      # Log out from DockerHub
      - name: Log out from DockerHub
        run: docker logout
